version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile  # Use Dockerfile for production
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
